version: '2.1'

services:

  lock-db:
    container_name: lock-db
    build: ./project/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  lock-service:
    container_name: lock-service
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5000:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@lock-db:5432/lock_dev
    depends_on:
      lock-db:
        condition: service_healthy
    links:
      - lock-db