version: '2.1'

services:

  file-service:
    container_name: file-service
    build: ./file_service
    volumes:
      - './file_service:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - MY_URL=http://192.168.99.100:5001
    
  file-service-2:
    container_name: file-service-2
    build: ./file_service
    volumes:
      - './file_service:/usr/src/app'
    ports:
      - 5002:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - MY_URL=http://192.168.99.100:5002

  directory-db:
    container_name: directory-db
    build: ./directory_service/project/db
    ports:
        - 5434:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  directory-service:
    container_name: directory-service
    build: ./directory_service
    volumes:
      - './directory_service:/usr/src/app'
    ports:
      - 5000:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@directory-db:5432/directory_dev
      - FS1_URL=http://192.168.99.100:5001
      - FS2_URL=http://192.168.99.100:5002
    depends_on:
      directory-db:
        condition: service_healthy
    links:
      - directory-db
