version: '2.1'

services:

  directory-db:
    container_name: directory-db
    build: ./project/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  directory-service:
    container_name: directory-service
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5000:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@directory-db:5432/directory_dev
    depends_on:
      directory-db:
        condition: service_healthy
    links:
      - directory-db