version: '2.1'

services:

  security-db:
    container_name: security-db
    build: ./project/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  security-service:
    container_name: security-service
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5000:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@security-db:5432/security_dev
    depends_on:
      security-db:
        condition: service_healthy
    links:
      - security-db